### PR TITLE
Create es.ts

### PR DESCRIPTION
**Pull request by carlosgonz0**

### CODE REVIEW

**Comment by rinigus** [comment]
Hi! As in the case of PL translation - Just FYI - please note that I am not working on loading translations in the wizard nor systemd-ask-passwd-gui. It would require separate handling of languages on the first install steps, if I understand process correctly.

**Comment by carlosgonz0** [comment]
Thank you. What about if you bump v.1.0.1 then @piggz pick up to Pinephone?

**Comment by piggz** [comment]
Its not a case of tagging a release, its that there is actually no support at all for translations (currently)

**Comment by carlosgonz0** [comment]
> Its not a case of tagging a release, its that there is actually no support at all for translations (currently)

Ok  i hopely  translations it fully fixed at some point.

**Pull request merged**
